export const teachersData = [
  { id: 1, name: "James Garner", subject: "Mathematics" },
  { id: 2, name: "Sarah Adams", subject: "English" },
  { id: 3, name: "Michael Thompson", subject: "History" },
  { id: 4, name: "Linda Watson", subject: "Science" },
  { id: 5, name: "David Smith", subject: "Chemistry" },
  { id: 6, name: "Susan Lee", subject: "Physics" },
  { id: 7, name: "William Johnson", subject: "Biology" },
  { id: 8, name: "Emily Harris", subject: "Geography" },
  { id: 9, name: "Christopher Clark", subject: "Computer Science" },
  { id: 10, name: "Patricia Robinson", subject: "Art" },
  { id: 11, name: "John Davis", subject: "Music" },
  { id: 12, name: "Megan Lewis", subject: "Physical Education" },
  { id: 13, name: "Brian Walker", subject: "Philosophy" },
  { id: 14, name: "Laura Hall", subject: "Psychology" },
  { id: 15, name: "Daniel Young", subject: "Sociology" },
  { id: 16, name: "Jessica King", subject: "Literature" },
  { id: 17, name: "George Allen", subject: "French" },
  { id: 18, name: "Anna Harris", subject: "Spanish" },
  { id: 19, name: "Matthew Scott", subject: "German" },
  { id: 20, name: "Karen Mitchell", subject: "Italian" },
  { id: 21, name: "Mark Nelson", subject: "History" },
  { id: 22, name: "Deborah Perez", subject: "Economics" },
  { id: 23, name: "Richard Carter", subject: "Law" },
  { id: 24, name: "Linda Stewart", subject: "Business Studies" },
  { id: 25, name: "Brian Evans", subject: "Engineering" },
  { id: 26, name: "Julia Morris", subject: "Health Education" },
  { id: 27, name: "Gary Cooper", subject: "Information Technology" },
  { id: 28, name: "Nancy Bennett", subject: "Drama" },
  { id: 29, name: "Jessica Foster", subject: "Design and Technology" },
  { id: 30, name: "Anthony Wright", subject: "Religious Studies" }
];
