export const studentsData = [
  {
    id: 1233554,
    name: 'Julius Aghaowa',
    class: 'VII A',
    date: 'March 25, 2021',
    parent: 'Aliu James',
    city: 'Lagos',
  },
  {
    id: 1233555,
    name: 'Maryam Hassan',
    class: 'VII A',
    date: 'April 10, 2021',
    parent: 'Amina Hassan',
    city: 'Abuja',
  },
  {
    id: 1233556,
    name: 'Chidi Okafor',
    class: 'VII B',
    date: 'May 5, 2021',
    parent: 'Ngozi Okafor',
    city: 'Enugu',
  },
  {
    id: 1233557,
    name: 'Sarah Eze',
    class: 'VII C',
    date: 'June 12, 2021',
    parent: 'Oluchi Eze',
    city: 'Port Harcourt',
  },
  {
    id: 1233558,
    name: 'John Ochieng',
    class: 'VII B',
    date: 'July 8, 2021',
    parent: 'Moses Ochieng',
    city: 'Kano',
  },
  {
    id: 1233559,
    name: 'Hannah Adeyemi',
    class: 'VII A',
    date: 'August 14, 2021',
    parent: 'Adeola Adeyemi',
    city: 'Ibadan',
  },
  {
    id: 1233560,
    name: 'David Oluwaseun',
    class: 'VII C',
    date: 'September 3, 2021',
    parent: 'Oluwaseun David',
    city: 'Abuja',
  },
  {
    id: 1233561,
    name: 'Evelyn Okoro',
    class: 'VII A',
    date: 'October 16, 2021',
    parent: 'Chukwuemeka Okoro',
    city: 'Benin',
  },
  {
    id: 1233562,
    name: 'Samuel Ndubuisi',
    class: 'VII B',
    date: 'November 20, 2021',
    parent: 'Olu Ndubuisi',
    city: 'Kaduna',
  },
  {
    id: 1233563,
    name: 'Vivian Onuoha',
    class: 'VII C',
    date: 'December 5, 2021',
    parent: 'Chima Onuoha',
    city: 'Jos',
  },
  {
    id: 1233564,
    name: 'Tolu Akinlade',
    class: 'VII A',
    date: 'January 14, 2022',
    parent: 'Bola Akinlade',
    city: 'Lagos',
  },
  {
    id: 1233565,
    name: 'Oluwafunmilayo Bello',
    class: 'VII B',
    date: 'February 21, 2022',
    parent: 'Abiodun Bello',
    city: 'Ilorin',
  },
  {
    id: 1233566,
    name: 'Ruth Onwuka',
    class: 'VII C',
    date: 'March 30, 2022',
    parent: 'Chinonso Onwuka',
    city: 'Warri',
  },
  {
    id: 1233567,
    name: 'Chuka Ugwuanyi',
    class: 'VII A',
    date: 'April 15, 2022',
    parent: 'Chioma Ugwuanyi',
    city: 'Aba',
  },
  {
    id: 1233568,
    name: 'Ifeoma Nwachukwu',
    class: 'VII B',
    date: 'May 10, 2022',
    parent: 'Ogechi Nwachukwu',
    city: 'Owerri',
  },
  {
    id: 1233569,
    name: 'Kofi Adebayo',
    class: 'VII C',
    date: 'June 18, 2022',
    parent: 'Sade Adebayo',
    city: 'Akure',
  },
  {
    id: 1233570,
    name: 'Grace Obinna',
    class: 'VII A',
    date: 'July 25, 2022',
    parent: 'Chuka Obinna',
    city: 'Abuja',
  },
  {
    id: 1233571,
    name: 'Daniel Ojo',
    class: 'VII B',
    date: 'August 4, 2022',
    parent: 'John Ojo',
    city: 'Ogun',
  },
  {
    id: 1233572,
    name: 'Angela Okonkwo',
    class: 'VII C',
    date: 'September 15, 2022',
    parent: 'Emeka Okonkwo',
    city: 'Benue',
  },
  {
    id: 1233573,
    name: 'Victor Nwosu',
    class: 'VII A',
    date: 'October 9, 2022',
    parent: 'Nnena Nwosu',
    city: 'Lagos',
  },
]